detections:
  classes:
  - 0
  - 1
  - 2
  - 3
  - 4
  conf_threshold: 0.25
  imgsz: 640
  iou_threshold: 0.5
system:
  character_model: yolo11s.pt
  data_path: data/traffic_video.avi
  device: cuda
  license_model: lp_yolo11s.pt
  output_dir: output
  save: false
  tracker: sort
  vehicle_model: detect_gtvn.pt
tracking:
  bytetrack:
    conf_threshold: 0.1
    cost_function: iou
    high_conf_iou_threshold: 0.5
    high_conf_threshold: 0.5
    low_conf_iou_threshold: 0.4
    low_conf_threshold: 0.1
    max_age: 60
    min_hits: 5
  sort:
    conf_threshold: 0.25
    cost_function: iou
    iou_threshold: 0.5
    max_age: 60
    min_hits: 5
violation:
  fps: 30
  padding: 30
  video_proof_duration: 3
